### ISSUE TITLE
What is `package.json` for?

### ISSUE THREAD

**Issue by kenji-miyake** [tier4/pre-commit-hooks-ros#18]
It seems a dummy.
https://github.com/tier4/pre-commit-hooks-ros/blob/b5aa698e1409deaf1974533750b0b51b2e4f8c47/package.json

**Comment by KeisukeShima** [comment]
It is used for JavaScript hooks.
https://github.com/igorshubovych/markdownlint-cli

For now, we don't have a plan to create JavaScript hooks. So I think it can be removed.
I will create PR soon.
